utils/views.py
Update utils/views.py line 155 to match peering_manager/views.py line 39. This fixes #34.
Fixes #34
=> Change django.utils.http.is_safe_url() in utils/views.py

docs/setup/peering-manager.md
=> Changed the text doc a little bit in order to make it more readable

peering/forms.py
_No issue has been created concerning this PR._
* Fix old broken github-wiki link in peering/forms.py
=> peering: Fix old wiki-link in forms.py

peering/views.py
Permissions issue with IXConfig view
=> remove PermissionRequiredMixin from IXConfig view

docs/config-template.md, docs/index.md, docs/integration.md, docs/man.md, docs/setup/logging.md, docs/setup/peering-manager.md, docs/setup/scheduled-tasks.md, docs/setup/upgrading.md, docs/setup/web-server.md, mkdocs.yml
Documentation to help with #90
=> Documentation changes (formatting, order, other modifications, IOS-XR Template Example)

docs/setup/postgresql.md
=> Document move from SQLite to PostgreSQL.

docs/config-template.md
Add an Arista EOS template example to documentation.
=> Add Arista EOS template example

peering/management/commands/update_peering_session_states.py
Fix internet_exchance used method for polling peering sessions
=> Fix internet_exchance method for polling sessions

peering/api/nested_serializers.py
=> Add prefix limits to nested AS results

peering/filters.py
=> Also filter for slug when searching for IX

.pre-commit-config.yaml, docs/templates/index.md, docs/templates/objects/autonomoussystem.md, docs/templates/objects/bgpgroup.md, docs/templates/objects/community.md, docs/templates/objects/directpeeringsession.md, docs/templates/objects/internetexchange.md, docs/templates/objects/internetexchangepeeringsession.md, docs/templates/objects/router.md, docs/templates/objects/routingpolicy.md, scripts/documentation/generate_template_doc.py
=> Add script to generate template documentation.

docs/templates/arista-eos.md
Update to use new variable names & make use of new features. Support IX Peering only for now.
=> Update Arista EOS template

docs/templates/arista-eos.md
Fix local_asn to use variable & filter policies properly so that all will also match, as well as specific AFI
=> Update arista-eos Template in docs

peering/api/serializers.py, peeringdb/api/serializers.py, peeringdb/api/urls.py, peeringdb/api/views.py, peeringdb/filters.py
- Exposes the encrypt_passwords field for the Router object 
- Adds REST end points for accessing the locally cached PeeringDB Network and Contacts
=> Rest api enhancements

peering/forms.py, peering/models.py, peering/views.py
- Add a checkbox for Poll BGP State when bulk editing Internet Exchanges
- Stabilize sorting of various tables
- Add BGP Session state to Autonomous System IX/BGPGroup Session tables
=> Ui improvements

peering/views.py
The session counts in ASListView and RouterListView were wrong/missing.
=> Fix router ix session count

docs/setup/8-prometheus.md, mkdocs.yml, peering_manager/settings.py, peering_manager/urls.py, requirements_dev.txt, requirements_prometheus.txt
This PR implements the proposed metrics endpoint in Issue #286
=> Add Prometheus endpoint

docs/models/peering/router.md
- Added remark about the "Ping" button.
- Added section about how to configure access using SSH
=> Added remark about the "Ping" button.

peering/urls.py, peering/views.py, templates/_base.html, templates/peering/provisioning/_base.html, templates/peering/provisioning/peers.html
Closes #64 
- Created Provisioning tab in UI
- Created "All Available Peers" page under Provisioning. This shows all available peers on all configured IXs
=> Create Provisioning & All Peers

templates/peering/autonomoussystem/inc/internet_exchange_peering_sessions_table.html
Closes: #319 
Allow user to add an IX Session directly from the ASN IX Peers view.
=> PM-319 - Add IX Session from ASN

peering/models/models.py
- Better log message on failure
=> Update Error to display Driver & Platform on NAPALM Failure

templates/peering/community/details.html
=> Fix broken HTML tag in community detail view

docs/configuration/optional-settings.md, docs/configuration/required-settings.md, docs/container.md, docs/models/peering/autonomoussystem.md, docs/models/peering/internetexchange.md, docs/models/peering/router.md, docs/models/peering/routingpolicy.md, docs/setup/1-postgresql.md, docs/setup/3-peering-manager.md, docs/setup/4b-nginx.md, docs/setup/5-logging.md, docs/setup/uwsgi.md, docs/templating/examples/cisco-iosxr-as196610.md, docs/templating/examples/tutorial-cisco-ios.md, docs/templating/examples/tutorial-cisco-iosxr.md, docs/templating/index.md, docs/templating/tutorial/as-template.md, docs/templating/tutorial/communities.md, docs/templating/tutorial/index.md, docs/templating/tutorial/policies.md, docs/templating/tutorial/tags.md, docs/user-interface.md, mkdocs.yml
This PR adds a new tutorial on templating to the documentation.
It also fixes some other minor imperfections in the documentation.
=> Templating tutorial

netbox/api.py
#508 
Not sure this is the best fix, but it seems to be working in my environment.
=> Handle generator returned by pynetbox

docs/setup/3-peering-manager.md
Chqnge rq to rqworker for upgrade.sh output
=> Update of rqworker service Documentation 

.github/ISSUE_TEMPLATE/bug_report.yml, .github/workflows/ci.yml, README.md, tox.ini
Make sure Peering Manager behaves has expected with Python 3.11.
=> Add testing with Python 3.11

templates/users/login.html
- add a conditional button to the login form to redirect to SAML2 SSO login when configured
=> saml2: add conditional SAML2 SSO login button

docs/setup/8-scheduled-tasks.md
1. Change to use absolute paths
2. `poll_peering_sessions --all` changed to `poll_bgp_sessions` in a recent version
=> Docs: Update Scheduled Tasks->CRON

docs/configuration/index.md, docs/setup/3-peering-manager.md
This adds documentation on how to run multiple rqworkers.
=> Explain how to run multiple rqworkers

docs/integrations/napalm.md
Fix a simple typo in the documentation.
=> fix(documentation): typo in napalm

peering/filtersets.py
Closes https://github.com/peering-manager/peering-manager/issues/866
Add value to searchable fields on CommunityFilterSet
=> Add value as searchable on CommunityFilterSet

peering/filtersets.py
Closes https://github.com/peering-manager/peering-manager/issues/864
Add comments to searchable fields on FilterSet for Direct and InternetExchangePeeringSessions
=> Add comments to searchable fields on FilterSet for Direct and InternetExchangePeeringSessions

project-static/css/base.css, project-static/js/base.js, project-static/js/colour-mode.js, templates/_base.html
This PR implements support for dark and light modes based on the Bootstrap 5.3 feature.
There are also changes in the top and side bars to fit with both colour modes.
=> Rework web UI base to support dark and light modes

docs/templating/examples/tutorial-vyos.md, docs/templating/index.md, mkdocs.yaml
Added VyOS template example/tutorial
=> Vyos Template

templates/peering/directpeeringsession/list.html, templates/peering/internetexchangepeeringsession/list.html
Add possibility for bulk edit to internet exchange/direct peering session list views.
=> Add bulk edit to session list views
