- peering/tables.py
- project-static/js/base.js
- templates/_base.html
- templates/peering/session/direct/details.html
- templates/peering/session/internet_exchange/details.html
This PR aims to close #69 by displaying comments (being peering session's or other's) when appropriate. This means that comments should be displayed to user to avoid them taking unnecessary actions. There is a pretty good summary of this in the previously mentioned issue.
> Display comments when appropriate

- docs/config-template.md
Fixes syntax error in EOS template, adds missing endif in sessions max_prefixes output.
> Add missing endif

- docs/config-template.md
Add missing closing } for IPv6 sessions to generate valid configuration.
> Fix JunOS template in the documentation

- docs/templates/index.md
Links at the bottom of Writing Templates page to examples had invalid URL.
> Fix links to template examples

- docs/setup/3-web-server.md
When the command variable is listed before the directory variable, supervisor runs the command before it has changed to the specified directory.
Not sure if this is a known bug, but I've seen other people with the same issue [https://serverfault.com/a/834182](https://serverfault.com/a/834182).
* Moves the directory variable so that it comes before the command variable.
> Put directory variable above command variable in docs

- peering/views.py
Appends a number to the duplicate slug instead of rejecting the request.
> IX import from PeeringDB will append number to slug if detected duplicate

- docs/templates/cisco-iosxr.md
Updated to match the latest router deployment configuration
Preview of generated config
```
router bgp 123456
neighbor 2001:7f8::2a:0:1
remote-as 42
description Packet Clearing House AS42 (AS-PCH)
use neighbor-group ng6-PEERING
address-family ipv6 unicast
maximum-prefix 600 95 restart 15
```
> updated cisco iosxr router deploy template

- project-static/css/base.css
Issue #158 
In the base.css added the class for the list-group-item to fix the position on the screen where the changelog seems to go over the end line
> Fix for issue #158 where changelog shows funny on windows pcs

- docs/templates/cisco-iosxr.md
Cisco IOS XR template example was not wrapped in
a code block.
> docs: fix missing codeblock

- docs/templates/cisco-iosxr.md
This updates two things on the XR template:
1. Use 'my_asn' variable instead of hard-coded ASN for the 'router bgp X' portion.
2. Fix spelling of family (was familiy) in variable names.
> IOS-XR Template Update

- docs/configuration/required-settings.md
- docs/templates/cisco-iosxr.md
- peering/tests/test_api.py
- peering/tests/test_models.py
Addresses using documentation prefixes in tests and documentation as noted in #159.
> Update documentation and tests to use rfc5737 addresses

- peering/__init__.py
- peering/tests/test_functions.py
While people usually use AS-xxxx for simple macros, when using
hierarchical macros, some are not always using "AS-" as a prefix for
each part. For example <https://www.peeringdb.com/net/2273> is using
AS16211:RS-ANNOUNCED which is invalid. However, there is little gain
of not accepting this macro as this makes the final configuration more
secure.
This commit removes the extra check about having AS- in the macro
name.
> Be more liberal in what is accepted as an AS-SET

- docs/configuration/optional-settings.md
I added the PeeringDB settings to the documentation, like PEERINGDB_USERNAME and PEERINGDB_PASSWORD.
> add PeeringDB settings to documentation

- peering/forms.py
- peering/tables.py
- peering/views.py
- peeringdb/views.py
- users/middleware.py
- users/views.py
- utils/api/views.py
- utils/crypto/junos.py
- utils/filters.py
- utils/middleware.py
- utils/views.py
Removes all unused imports throughout the project. Let me know if I missed something or if I removed too much. I found the unused imports using [LGTM](https://lgtm.com/projects/g/respawner/peering-manager/?mode=list) and verified manually as good as I could (and using `flake8`).
> Remove unused imports

- docs/setup/2-peering-manager.md
In the current documentation, you want the repository cloned into /opt/peering-manager. 
Todo this `git clone https://github.com/respawner/peering-manager.git .` need to be changed into `git clone https://github.com/respawner/peering-manager.git`
> Clone repository into /opt/peering-manager

- docs/configuration/optional-settings.md
- peering_manager/settings.py
Introduces an attempt to obtain the local timezone from `/etc/timezone` prior to defaulting to UTC where TIME_ZONE is not specified.
> Fix default timezone

- peering/management/commands/configure_routers.py
Typo in a description under configure_routers.py.
> Fix typo in configure_routers.py

- peering/models.py
In find_potential_ix_peering_sessions() network_ixlan.ipaddr6/ipaddr4 fields were being cast to IPv4/6Address objects and back to string again unnecesarily, which was causing the list comparison to always fail and constantly update the potential_internet_exchange_peering_sessions field. Since the ipaddr6/ipaddr4 fields are already the right type, they can just be added directly to the list
> Fix list comparison in find_potential_ix_peering_sessions()

- peering/models.py
- peering/urls.py
- peering/views.py
- peeringdb/tables.py
- templates/peering/as/_base.html
- templates/peering/as/peers.html
Added new tab to AS view where you can add missing sessions from in bulk
Based on the view for building missing sessions for an IX
Adds 2 new views. One to display the missing sessions, another to receive the POST and build the form to review the changes. 
A new ASPeerRecordTable is defined since we want to display slightly different information than the original PeerRecordTable. 
New method for AutonomousSystems class that returns a query set of PeerRecords by matching the ipaddr6 and ipaddr4 with the missing_sessions list. 
New static method for InternetExchangePeeringSession to factor out the search for possible InternetExchange objects matching a PeerRecord. 
The missing sessions only shown once for each IX, even if you have multiple connections to the IX. However, these get expanded …
> New feature to allow building missing sessions for an AS

- .github/workflows/testing.yml
- .gitignore
- docs/configuration/optional-settings.md
- peering/tables.py
- peering/views.py
- peering_manager/configuration.example.py
- peering_manager/settings.py
- requirements.txt
- scripts/development/dev-stack.yml
Use Redis as cache to speed data retrieval and reduce the number of SQL queries to be performed in a multi-users environment.
Some views can be quite expensive to load due to heavy SQL queries. Caching results of queries into Redis will speed views rendering by avoiding SQL queries that we already executed.
This add `django-cacheops` as a dependency, though the use of Redis is not yet required. It probably will be at some points to add more features.
> Use Redis as cache

- peering/forms.py
- peering/models.py
- peering/urls.py
- peering/views.py
- peeringdb/forms.py
- project-static/js/forms.js
- templates/peering/as/inc/direct_peering_sessions_table.html
- templates/peering/bgp-group/inc/sessions_table.html
- templates/peering/ix/inc/sessions_table.html
- templates/peering/router/direct_peering_sessions.html
- templates/peering/router/inc/sessions_table.html
- utils/forms.py
- utils/templates/widgets/select_api.html
- utils/views.py
Huge data preloading due to the way Django work for `<select>` (multiple) elements can be quite a performance killer. This PR is leveraging the API to avoid loading all the data by just loading the one that are already selected or by loading none of them and letting the API do its work.
This PR also includes a better way to redirect user after form submits by using a mixin class instead of overriding a method.
> Leverage API driven select element

- utils/views.py
* The ModelViewList.post() method doesn't support additional kwargs which are supplied in some views causing the request to fail 
* The queryset attribute needs to be initialized otherwise it can be None, which will cause the construction of TableConfigurationForm to fail.
> Fix user preference update in *PeeringSessions views

- docs/setup/migrate-to-systemd.md
This is a PR related to https://github.com/respawner/peering-manager/issues/269 . 
a - was changed to a _
> correction to the doc

- docs/configuration/optional-settings.md
- peering_manager/settings.py
- Changed default host from rr.ntt.net to whois.radb.net. RADB is a more
authoritative IRR source. #281
> Default IRR Host Update

- peering/forms.py
Closes #233 
- Modified Slug help text to display a warning that the operational state of a device may change if the slug is being used in config generation.
> Modify IX & BGP Slug Warnings

- peering/management/commands/grab_prefixes.py
If bgpq3 errors out for some reason, then the entire grab_prefixes command will stop. 
You may want to ignore transient errors and not have the entire process stop
Added a `--ignore-errors` option so the loop will continue processing all the ASN's
> Grab prefixes fix

- docs/setup/7-scheduled-tasks.md
This PR enhances the documentation by showing an alternative way to run tasks instead of using cron.
This PR depends on https://github.com/peering-manager/contrib/pull/2
> Add section about systemd timers instead of cron

- peering/api/serializers.py
Return `service_reference` in the API calls for `/api/peering/direct-peering-sessions/` and `/api/peering/internet-exchange-peering-sessions/`
> Display service_reference via API

- CHANGELOG.md
- peering/forms.py
- templates/_base.html
- templates/home.html
- templates/peering/configuration/details.html
- templates/peering/email/details.html
- utils/templatetags/helpers.py
I have stumbled upon some broken links to documentation in the code.
Some discussion points:
1. Maybe we don't want to let documentation links show to latest but to the corresponding release?
2. Should we do the same to the line I commented in the changelog? As far as I can see, the documentation for that old release does not exist any more?
> Fix or comment broken documentation links

- peering/management/commands/import_all_ix_sessions.py
Add Management command to Import all IX sessions. This can be used when Peering Manager is disabled for a long period of time or mass manual changes across Multiple IX's are done requiring a resync into Peering Manager. This command is built using the new Connection model. 
Closes: #400
> PM-400 - Import all IX Sessions

- peering/models/abstracts.py
Exclude all the policies from BGP Group and AS that are not universal and don't match the IP family.
> Filter out policies that don't match the session IP Family

- docs/configuration/optional-settings.md
- peering/models/models.py
- peering_manager/settings.py
Issue #471. 
*  Cache the results of get_bgp_neighbors_detail()
* Add a `CACHEOPS_BGP_DETAIL_TIMEOUT` to settings to control the timeout. 
* Need to decide what a reasonable default value is here.
> Set up a configurable cache time around the results of get_bgp_neighbors_detail()

- templates/home.html
> Fix typo in the template

- docs/setup/4b-nginx.md
With this configuration within nginx, http and https links within
the API are rendered correctly when you are using https for the virtualhost.
With the former ones, https usage in API link is broken.
> Changing NGINX Proxy Configuration in Documentation

- peering/models/models.py
This doesn't fix a new problem, but it's an alternate fix to #501 that I think is a bit cleaner. Instead of looping over the IX's routers and then trying to use the neighbor IPs to find the connection back to the IX, this approach loops over the IX's connections so the current connection is available when performing the session lookup.
This also avoids instantiating ipaddress objects for each neighbor and the problem of pre-1.4.5 connection addresses having /32 or /128 subnets.
> Loop over connections instead of routers

- net/models.py
- peering/views.py
- peeringdb/models.py
When importing "LINX Manchester" as AS41495, we found that our ASN had two records in PeeringDB, one of which looked like stale data (though it could be an artefact of how we are a LINX ConneXions Partner and so have a port with no IP address, in addition to a VLAN within that port providing peering LAN services to our AS).
To confirm this issue we set our local instance of PM v1.6.0 to show this text for entries with no IPv4/IPv6 address:
What I have done in this very small PR is to catch the ValueError and ensure `cidr4` and `cidr6` return `None` instead.  This at least allows the IXs to be imported, even if the IP addresses aren't there for these "ghost" connections:
> workaround runtime import IX when PDB data has connections with no IPs

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/workflows/ci.yml
- README.md
- docs/configuration/optional-settings.md
- docs/development/getting-started.md
- docs/index.md
- docs/setup/1-postgresql.md
- docs/setup/2-redis.md
- docs/setup/3-peering-manager.md
- docs/setup/5-logging.md
- extras/__init__.py
- peering/__init__.py
- peering/migrations/0001_v1.0.0.py
- peering/migrations/0022_auto_20181116_2226.py
- peering/migrations/0044_auto_20190513_2153.py
- peering/migrations/0045_auto_20190514_2308.py
- peering/migrations/0065_auto_20201025_2137.py
- peering_manager/settings.py
- peering_manager/tests/test_jinja2.py
- peering_manager/views/generics.py
- requirements.txt
- templates/includes/pagination.html
- templates/users/_user.html
- tox.ini
- users/views.py
- utils/migrations/0001_v1.0.0.py
- utils/migrations/0005_tag_taggeditem.py
- utils/migrations/0006_auto_20200626_2340.py
Closes #532
* Bumps Django to 4.0
* Tweak old migrations to avoid introducing [no-op migrations](https://docs.djangoproject.com/en/4.0/releases/4.0/#migrations-autodetector-changes)
* Remove dependency on `is_safe_url()` function
> Use of Django 4 and Python < 3.8 deprecation

- docs/templating/examples/juniper-junos.md
- Clarify `shutdown` was added in Junos 19.1
> Docs: Template: Junos: Mention inactive

- docs/models/extras/exporttemplate.md
- Replace fqdn with generic environment variable
> Docs: hotfix: replace fqdn with generic variable

- docs/models/extras/exporttemplate.md
in the session ip address field. Otherwise, LibreNMS will return an error if the ip address field includes an subnet mask.
> Docs: Export template, use `ip` for avoid subnet mask

- docs/setup/6a-ldap.md
Provided an example LDAP search string to allow UPN logins as well as Userid logins.
New information, not a fix.
> example to allow UPN logins

- docs/setup/3-peering-manager.md
- docs/setup/4a-apache2.md
- docs/setup/4b-nginx.md
Update apache2, nginx, and gunicorn sections to mention how to have peering-manager run on the IPv6 loopback address instead of the IPv4 loopback address.
> Docs: Include information to have gunicorn listen on IPv6 ::1

- templates/utils/templatetags/tag.html
Template-Tag 'Tag' does set get parameter tag to <tag.pk>
Filtering needs <tag.slug> to work as it seems to be intended.
This change fixes this behaviour.
> Fix filtering on tag in TagColumn

- devices/models.py
Fix platform absolute url showing peering:router_list filtered on platform as it seems to be intended
> Fix platform absolute url

- docs/setup/1-postgresql.md
When using PostgreSQL version 15 or above the initial database migration failes due to missing permissions.
This patch updates the installation documentation, adding the commands necessary.
> Update installation documentation for PostgreSQL 15

- peering_manager/jinja2/loaders.py
- peering_manager/tests/test_jinja2.py
jinja2/loaders.py::PeeringManagerLoader::get_source return type to allow using include_* multiple times, see testcase runs here:
https://github.com/rwielk/peering-manager/actions
First one failing indicating multiple use of include_* for same template fails, second fixing this behaviour by fixing get_source returns.
> Bugfix: Allow multiple use of same template include

- docs/templating/examples/juniper-junos.md
- docs/templating/tutorial/index.md
Added route-filter examples to the documentation, tried to best match the IOS and IOS-XR examples for the same feature. 
Updated docs/templating/examples/juniper-junos.md example template to include per ASN route-filters
Updated docs/templating/tutorial/ index.md to include an example of Juniper style route-filters
> Add Juniper per ASN route filters to the tutorial and example templates

- docs/configuration/miscellaneous.md
- peering_manager/settings.py
This PR implements a census report call via HTTP POST when a worker start.
Users can disable this reporting by setting `CENSUS_REPORTING_ENABLED` to `False` in the configuration file.
> Add census report call on worker start

- peering/migrations/0102_move_router.py
Fixes:
Closes https://github.com/peering-manager/peering-manager/issues/870
Migration dependency missing
> Fix migration dependencies of router move in peering app

- peering/models/abstracts.py
Fix merged_communities on Session-Model for direct peering session with bgp_group=null
Closes #874
> Fix merged_communities on Session-Model for direct peering session

- peering_manager/middleware.py
- peering_manager/views/errors.py
Log 500 for api views, on programming errors and on import errors using djangos log_response mechanism
#888
> Log 500 for api views, on programming errors and on import errors

- devices/models.py
Fix calling job.log_warning with wrong kwarg: It's object, not obj, s. https://github.com/peering-manager/peering-manager/blob/main/core/models/jobs.py#L190
> Fix calling job.log_warning with wrong kwarg

- peering/functions.py
This change allows null/empty bgpq arguments by only including options for non-null arguments.
The fix involves minor changes in peering/functions.py in how the bgpq command is constructed.
> handle null bgpq arguments

- peering/functions.py
- peering/models/__init__.py
- peering/tests/test_functions.py
As bgpq4 is able to resolve an AS-SET even if it is prefixed with the IRR to use as source, we do not need to remove it. In fact, it's even better to keep it so bgpq4 can do its job properly.
In the case of bgpq3, we still remove the source from the AS-SET string and try to limit the source with it. If the parsed source is not in the sources specified in the settings, we will query all sources.
> Keep IRR source in AS-SET for bgpq4

- devices/models.py
- docs/templating/jinja2/filters.md
- peering_manager/jinja2/filters.py
This PR adds the possiblity to list the associated BFD profiles of a router.
That allows the creation of BFD profiles on supported routers without having to rely on a loop on the sessions, which can cause duplicates of the same BFD profile.
The new Jinja2 filter was named `bfds`.
The PR includes updates to both the documentation and the codebase to support this new functionality.
* **Documentation Update**: Added a description and example usage of the `bfds` filter in `docs/templating/jinja2/filters.md`. This explains how to use the filter to fetch BFD profiles for a router.
* **Filter Functionality**: Implemented the `bfds` filter in `peering_manager/jinja2/filters.py`. The filter retrieves all BFD profiles that have at least one session configured on the specified router. It raises a …
> Add support for listing BFD profiles of a router in templates

- devices/filtersets.py
- devices/forms.py
- devices/models.py
- peering/api/views.py
- peering/filtersets.py
- peering/forms.py
- peering/management/commands/grab_prefixes.py
- peering/models/__init__.py
- peering/views.py
- peering_manager/constants.py
- peeringdb/forms.py
- peeringdb/jobs.py
- peeringdb/management/commands/peeringdb_sync.py
This change should fix #938 by ensuring that we always defer `prefixes` retrieval for autonomous systems even when AS objects are selected as related objects.
> Closes #938: Always defer AS `prefixes` field
